# Generated by Django 3.2 on 2022-05-09 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0003_author_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='sort_title',
            field=models.CharField(default=12, max_length=256),
            preserve_default=False,
        ),
    ]
