# Generated by Django 3.2 on 2022-07-17 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0006_auto_20220717_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awarddetails',
            name='award',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books_app.award'),
        ),
        migrations.AlterField(
            model_name='awarddetails',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books_app.book'),
        ),
    ]
