# Generated by Django 3.2 on 2022-07-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0007_auto_20220717_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awarddetails',
            name='award_year',
            field=models.PositiveIntegerField(),
        ),
    ]
