# Generated by Django 3.2 on 2022-07-19 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0008_alter_awarddetails_award_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['sort_name']},
        ),
    ]
