# Generated by Django 3.2 on 2022-07-20 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0010_alter_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='books',
            field=models.ManyToManyField(blank=True, null=True, through='books_app.AwardDetails', to='books_app.Book'),
        ),
    ]
