# Generated by Django 3.2 on 2022-07-20 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0011_alter_award_books'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='award',
            options={'ordering': ['sort_name']},
        ),
        migrations.AlterModelOptions(
            name='awarddetails',
            options={'ordering': ['award_year']},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['sort_title']},
        ),
    ]
