# Generated by Django 3.2 on 2022-07-20 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0012_auto_20220720_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='books',
            field=models.ManyToManyField(blank=True, through='books_app.AwardDetails', to='books_app.Book'),
        ),
    ]
